// Code generated by wxbot project. DO NOT EDIT.
// Source: github.com/yqchilde/wxbot/engine/plugins/generate.go

package plugins

import (
	// 百度百科
	_ "github.com/yqchilde/wxbot/plugins/baidubaike"

	// 肯德基疯狂星期四骚话
	_ "github.com/yqchilde/wxbot/plugins/crazykfc"

	// 公众号消息监控转发
	_ "github.com/yqchilde/wxbot/plugins/ghmonitor"

	// 群组管理相关
	_ "github.com/yqchilde/wxbot/plugins/manager"

	// 表情包原图
	_ "github.com/yqchilde/wxbot/plugins/memepicture"

	// 摸鱼办
	_ "github.com/yqchilde/wxbot/plugins/moyuban"

	// 拼音缩写翻译
	_ "github.com/yqchilde/wxbot/plugins/pinyinsuoxie"

	// 漂亮妹妹
	_ "github.com/yqchilde/wxbot/plugins/plmm"

	// 天气查询
	_ "github.com/yqchilde/wxbot/plugins/weather"

	// 每日早报
	_ "github.com/yqchilde/wxbot/plugins/zaobao"

	// 聊天热词
	_ "github.com/yqchilde/wxbot/plugins/wordcloud"

	// 查wxId
	_ "github.com/yqchilde/wxbot/plugins/chaid"

	// 有道翻译
	_ "github.com/yqchilde/wxbot/plugins/youdaofanyi"

	// 自动加好友
	_ "github.com/yqchilde/wxbot/plugins/friendadd"

	// 选择困难症帮手
	_ "github.com/yqchilde/wxbot/plugins/choose"

	// 读取本地图片
	_ "github.com/yqchilde/wxbot/plugins/localimage"

	// 爬取图片到本地
	_ "github.com/yqchilde/wxbot/plugins/localimagespider"

	// ChatGPT聊天，优先级必须放到最低
	_ "github.com/yqchilde/wxbot/plugins/chatgpt"
)
