name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  changelog:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: npx changelogithub # or changelogithub@0.12 if ensure the stable result
        env:
          GITHUB_TOKEN: ${{secrets.WXBOT_TOKEN}}

  release:
    needs: changelog
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        go-version: [ '1.20' ]
    name: Release
    runs-on: ${{ matrix.platform }}
    permissions:
      contents: write
    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Install dependencies
        run: |
          sudo apt install upx

      - name: Build
        run: |
          export GOPROXY=https://goproxy.cn,direct
          go mod tidy
          make release version=${{ github.ref_name }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/*.tar.gz
